### ISSUE TITLE
BOM generation throwing "NameError: global name 'project' is not defined"

### ISSUE THREAD

**Issue by zen** [Toroid-io/kicad-ci-scripts#6]
Hi,

Still playing with your amazing tools, now I'm trying to generate BOM from drone-kicad plugin and came across this bug:

`
+ python2 -u /bin/ci-scripts/export_bom.py drone-kicad-sample
Initial recording window is set to:
X:0   Y:0    Width:800    Height:600
Adjusted recording window is set to:
X:0   Y:4    Width:800    Height:592
Your window manager appears to be Unknown

Initializing...
Output file: /drone/src/bitbucket.org/surge-cloud/ci-test/CI-BUILD/drone-kicad-sample/BOM/export_bom_screencast.ogv
Capturing!

(eeschema:73): Gtk-WARNING **: 16:09:15.006: Attempting to store changes into `/root/.local/share/recently-used.xbel', but failed: Failed to create file ?/root/.local/share/recently-used.xbel.MYASSZ?: No such file or directory

(eeschema:73): Gtk-WARNING **: 16:09:15.010: Attempting to set the permissions of `/root/.local/share/recently-used.xbel', but failed: No such file or directory
INFO:__main__:Open Tools->Generate Bill Of Materials
INFO:__main__:Run generate
INFO:export_util:Waiting for plot window...
INFO:export_util:Found plot window
INFO:__main__:Wait before shutdown
Shutting down....
   
Done.
Written 222562 bytes
(222562 of which were video data and 0 audio data)

..
Goodbye!
Traceback (most recent call last):
  File "/bin/ci-scripts/export_bom.py", line 89, in <module>
    export_bom(sys.argv[1])
  File "/bin/ci-scripts/export_bom.py", line 81, in export_bom
    project+'.xml',
NameError: global name 'project' is not defined
exit status 1
`

I think it should use prjfile var that is passed to export_bom() but didn't spend much time with that

**Comment by andresmanelli** [comment]
Hello, I'll check later today what's happening. Thanks for reporting the issue!

**Comment by andresmanelli** [comment]
Hello, could you check `toroid/drone-kicad:0.5.5` ? This should be fixed

**Comment by zen** [comment]
Working now, thank you very much!
